##############################################################
## 配置数据源信息
##############################################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hans?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 12345678